# Generated by Django 3.2.5 on 2021-07-14 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('journey_date', models.DateField()),
                ('seat_available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OfferRide',
            fields=[
                ('ride_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.ride')),
                ('origin_location', models.CharField(max_length=50)),
                ('destination_location', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('fare', models.IntegerField()),
            ],
            bases=('home.ride',),
        ),
    ]
