# Generated by Django 3.2.5 on 2021-07-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ride',
            name='journey_date',
            field=models.DateTimeField(),
        ),
    ]
