# Generated by Django 3.2.5 on 2021-07-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelBasics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Gender', max_length=1),
            preserve_default=False,
        ),
    ]
