# Generated by Django 3.2.5 on 2021-07-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelBasics', '0002_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Select your gender', max_length=1),
        ),
    ]
