# Generated by Django 3.2.5 on 2021-07-17 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelBasics', '0003_alter_person_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('FS', 'Full Stack'), ('FE', 'Front End'), ('BE', 'Backend')], default='department', max_length=2)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelBasics.person')),
            ],
        ),
    ]
