# Generated by Django 3.2.5 on 2021-07-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
