# Generated by Django 3.2.5 on 2021-07-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-updated_on']},
        ),
    ]
